services:
  - type: web
    name: doodle-studio
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    autoDeploy: true
